import {Fluid} from './solver.js';
import {Renderer} from './renderer.js';
import {scenes,terms} from './scenes.js';
const $=id=>document.getElementById(id),fluid=new Fluid(innerWidth<701?80:128),renderer=new Renderer($('fluid'),$('overlay'),fluid);
let index=0,elapsed=0,last=0,paused=matchMedia('(prefers-reduced-motion: reduce)').matches,scrub=30,frames=0,totalMs=0,auto=true;
const nav=$('timeline');scenes.forEach((s,i)=>{const b=document.createElement('button');b.setAttribute('aria-label',`${i+1}. ${s.name}`);b.title=s.name;b.onclick=()=>go(i);nav.append(b)});
terms.forEach(([key,label])=>{const row=document.createElement('label');row.className='term';row.innerHTML=`<span>${label}</span><input type="checkbox" checked aria-label="${label}" data-term="${key}">`;row.querySelector('input').onchange=e=>{fluid.options[key]=e.target.checked;sync()};$('terms').append(row)});
function sync(){document.querySelectorAll('[data-term]').forEach(el=>{el.checked=fluid.options[el.dataset.term]});const toggle=$('scene-toggle');if(toggle){const key=scenes[index].term;toggle.setAttribute('aria-pressed',fluid.options[key]);toggle.innerHTML=`<span class="switch-light"></span>${terms.find(t=>t[0]===key)[1]} ${fluid.options[key]?'on':'off'} <span>↔</span>`}if($('lab-note'))$('lab-note').textContent=(!fluid.options.pressure||!fluid.options.incompressibility)?'Pressure and volume constraint share one correction. It is now disabled.':'A two-dimensional window into fluid motion.'}
function setRe(value){const re=10**(1+Number(value)*.035);fluid.nu=.3/re;$('reynolds').value=value;$('reynolds-value').textContent=Math.round(re).toLocaleString();$('viscosity').value=Math.max(0,Math.min(100,(Math.log10(fluid.nu)+5)/3.5*100));$('viscosity-value').textContent=fluid.nu.toFixed(5);if($('scene-range')&&scenes[index].kind==='reynolds'){$('scene-range').value=value;$('range-value').textContent=`Re ≈ ${Math.round(re).toLocaleString()}`}}
$('reynolds').oninput=e=>setRe(e.target.value);$('viscosity').oninput=e=>{fluid.nu=10**(-5+Number(e.target.value)*.035);const v=Math.max(0,Math.min(100,(Math.log10(.3/fluid.nu)-1)/.035));$('reynolds').value=v;$('reynolds-value').textContent=Math.round(.3/fluid.nu).toLocaleString();$('viscosity-value').textContent=fluid.nu.toFixed(5)};
function pauseUI(){$('pause').textContent=paused?'▶':'Ⅱ';$('pause').setAttribute('aria-label',paused?'Play animation':'Pause animation');$('step').hidden=!paused;$('sim-label').textContent=paused?'PAUSED':'LIVE FLUID'}
$('pause').onclick=()=>{paused=!paused;pauseUI()};$('step').onclick=()=>{advance(1/30);renderer.draw(scenes[index].kind,elapsed,scrub)};
function reset(){fluid.clear();for(let j=0;j<100;j++){const a=j/99;fluid.splat(.5+.16*Math.sin(a*6),.77-a*.5,Math.cos(a*6)*.015,-.008,0,.12,.019);fluid.splat(.59+.12*Math.cos(a*7),.75-a*.5,-.013*Math.sin(a*7),-.01,1,.11,.017)}for(let y=1;y<=fluid.n;y++)for(let x=1;x<=fluid.n;x++){const px=x/fluid.n-.55,py=y/fluid.n-.48,w=Math.exp(-(px*px+py*py)/.035),k=x+y*fluid.s;fluid.u[k]+=-py*w*4;fluid.v[k]+=px*w*4}for(let j=0;j<25;j++)fluid.step(1/60)}
$('reset').onclick=()=>{for(const [k] of terms)fluid.options[k]=true;setRe(55);reset();sync()};
function range(label,value,handler){$('scene-controls').innerHTML=`<label class="control-label" for="scene-range"><span>${label}</span><output id="range-value"></output></label><input id="scene-range" type="range" min="0" max="100" value="${value}">`;$('scene-range').oninput=e=>{handler(Number(e.target.value));renderer.draw(scenes[index].kind,elapsed,scrub)};handler(value)}
function go(i){index=Math.max(0,Math.min(scenes.length-1,i));const s=scenes[index];document.body.dataset.kind=s.kind;renderer.resize();$('act').textContent=`ACT ${s.act===1?'I':'II'}  /  ${s.kicker}`;$('title').innerHTML=s.title;$('caption').textContent=s.caption;$('gesture').textContent=s.hint;$('scene-number').textContent=String(index+1).padStart(2,'0');$('chapter-name').textContent=s.name;$('prev').disabled=index===0;$('next').innerHTML=index===0?'Begin exploring <span>→</span>':index===12?'Back to the start <span>↺</span>':'Continue <span>→</span>';$('equation').hidden=s.kind!=='equation';$('lab').hidden=!['assemble','sandbox'].includes(s.kind);$('scene-controls').replaceChildren();if(s.term){$('scene-controls').innerHTML='<button id="scene-toggle" class="scene-toggle"></button>';$('scene-toggle').onclick=()=>{fluid.options[s.term]=!fluid.options[s.term];sync()}}
 if(s.kind==='viscosity'){$('scene-controls').insertAdjacentHTML('beforeend','<label class="control-label" for="local-viscosity" style="margin-top:20px">Thin → thick</label><input id="local-viscosity" type="range" min="0" max="100" value="40">');$('local-viscosity').value=$('viscosity').value;$('local-viscosity').oninput=e=>{$('viscosity').value=e.target.value;$('viscosity').dispatchEvent(new Event('input'))}}
 if(s.kind==='reynolds')range('From laminar to restless',55,value=>setRe(value));
 if(s.kind==='cascade')range('Follow the energy',30,value=>{scrub=value;$('range-value').textContent=value<30?'Large':value<70?'Smaller':'Smallest'});
 if(s.kind==='singularity'){range('Approach a hypothetical singularity',0,value=>{scrub=value;$('range-value').textContent=`${value}%`});$('scene-controls').insertAdjacentHTML('beforeend','<a class="scene-source" href="https://www.claymath.org/millennium/Navier-Stokes-Equation/" target="_blank" rel="noopener">The open problem · Clay Mathematics Institute ↗</a>')}
 if(['assemble','sandbox'].includes(s.kind)){for(const [key]of terms)fluid.options[key]=true}
 [...nav.children].forEach((b,j)=>{b.setAttribute('aria-current',j===index);b.classList.toggle('visited',j<index)});sync();$('story').classList.remove('fade-in');void $('story').offsetWidth;$('story').classList.add('fade-in');history.replaceState(null,'',`#${index}`);renderer.draw(s.kind,elapsed,scrub)}
$('prev').onclick=()=>go(index-1);$('next').onclick=()=>go(index===12?0:index+1);addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight'){e.preventDefault();go(index+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(index-1)}if(e.code==='Space'&&!['BUTTON','A'].includes(document.activeElement.tagName)){e.preventDefault();$('pause').click()}});addEventListener('hashchange',()=>go(Number(location.hash.slice(1))||0));
let pointer=null,strokes=0;
function ink(e){let p=renderer.position(e.clientX,e.clientY);if(p.x<0||p.x>1||p.y<0||p.y>1){p.x=Math.max(.05,Math.min(.95,p.x));p.y=Math.max(.05,Math.min(.95,p.y))}return p}
$('fluid').addEventListener('pointerdown',e=>{e.preventDefault();$('fluid').setPointerCapture(e.pointerId);const p=ink(e);pointer={...p,id:e.pointerId};strokes++;fluid.splat(p.x,p.y,0,-.08,strokes%2,1.3,.028);renderer.draw(scenes[index].kind,elapsed,scrub)});
$('fluid').addEventListener('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;const p=ink(e),dx=p.x-pointer.x,dy=p.y-pointer.y,len=Math.hypot(dx,dy),steps=Math.max(1,Math.ceil(len*fluid.n));for(let k=1;k<=steps;k++)fluid.splat(pointer.x+dx*k/steps,pointer.y+dy*k/steps,Math.max(-.6,Math.min(.6,dx*8)),Math.max(-.6,Math.min(.6,dy*8)),strokes%2,.4,.021);pointer={...p,id:e.pointerId};renderer.draw(scenes[index].kind,elapsed,scrub)});for(const event of ['pointerup','pointercancel','lostpointercapture'])$('fluid').addEventListener(event,()=>pointer=null);
function advance(dt){elapsed+=dt;if(auto&&fluid.options.time){const q=elapsed,x=.52+.13*Math.sin(q*.73);fluid.splat(x,.78,fluid.options.force?.02*Math.cos(q*1.3):0,fluid.options.force?-.05:0,0,dt*9,.016);fluid.splat(.65+.1*Math.sin(q*.61+2),.71,fluid.options.force?-.02*Math.cos(q):0,fluid.options.force?-.043:0,1,dt*8,.014)}fluid.step(dt)}
function tick(now){const dt=Math.min(1/30,(now-last)/1000||1/60);last=now;const start=performance.now();if(!paused)advance(dt);renderer.draw(scenes[index].kind,elapsed,scrub);totalMs+=performance.now()-start;frames++;requestAnimationFrame(tick)}
// Small inspectable diagnostics for numerical and browser QA; no network or tracking.
window.fluidLab={fluid,go,renderer,stats:()=>({grid:fluid.n,frames,meanWorkMs:totalMs/frames,strokes,scene:index,paused,divergence:fluid.divergence()}),setAuto:v=>auto=v};
setRe(70);reset();go(Number(location.hash.slice(1))||0);pauseUI();requestAnimationFrame(tick);
if(document.modelContext?.registerTool){const lifecycle=new AbortController();addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'navigate_fluid_scene',description:'Navigate to one of the thirteen fluid explanation scenes.',inputSchema:{type:'object',properties:{scene:{type:'integer',minimum:1,maximum:13}},required:['scene'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Number.isInteger(input.scene)||input.scene<1||input.scene>13)throw new Error('scene must be an integer from 1 to 13');go(input.scene-1);return{scene:input.scene,title:scenes[index].name}}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
