export class Renderer {
 constructor(canvas,overlay,fluid){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:false});this.overlay=overlay;this.o=overlay.getContext('2d');this.fluid=fluid;this.off=document.createElement('canvas');this.off.width=this.off.height=fluid.n;this.oc=this.off.getContext('2d');this.img=this.oc.createImageData(fluid.n,fluid.n);this.resize();window.addEventListener('resize',()=>this.resize())}
 resize(){this.w=innerWidth;this.h=this.canvas.parentElement.clientHeight;const d=Math.min(devicePixelRatio,2);for(const c of [this.canvas,this.overlay]){c.width=this.w*d;c.height=this.h*d;c.getContext('2d').setTransform(d,0,0,d,0,0)}this.box=this.w<=700?{x:0,y:this.h*.3,w:this.w,h:this.h*(this.h>1000?.3:.61)}:{x:this.w*.31,y:this.h*.02,w:this.w*.74,h:this.h*.91}}
 position(x,y){const b=this.box;return{x:(x-b.x)/b.w,y:(y-b.y)/b.h}}
 draw(kind,t,scrub){const {ctx:c,w,h,fluid:f}=this,px=this.img.data,n=f.n,s=f.s;for(let y=0;y<n;y++)for(let x=0;x<n;x++){let i=x+1+(y+1)*s,k=(x+y*n)*4,a=f.r[i],b=f.b[i],v=1-Math.exp(-a*2.6),z=1-Math.exp(-b*2.5);px[k]=8+Math.min(235,v*211+z*48);px[k+1]=14+Math.min(230,v*144+z*205);px[k+2]=19+Math.min(220,v*81+z*211);px[k+3]=255}this.oc.putImageData(this.img,0,0);c.fillStyle='#080e13';c.fillRect(0,0,w,h);const box=this.box;c.imageSmoothingEnabled=true;c.drawImage(this.off,box.x,box.y,box.w,box.h);
 // Fade the numerical domain into the page, preserving bright interior structure.
 let g=c.createLinearGradient(box.x,0,box.x+box.w,0);g.addColorStop(0,'#080e13');g.addColorStop(.13,'#080e1300');g.addColorStop(.84,'#080e1300');g.addColorStop(1,'#080e13');c.fillStyle=g;c.fillRect(box.x,box.y,box.w,box.h);g=c.createLinearGradient(0,box.y,0,box.y+box.h);g.addColorStop(0,'#080e13');g.addColorStop(.16,'#080e1300');g.addColorStop(.82,'#080e1300');g.addColorStop(1,'#080e13');c.fillStyle=g;c.fillRect(box.x,box.y,box.w,box.h);
 if(w>700){g=c.createLinearGradient(0,0,w*.62,0);g.addColorStop(0,'#080e13');g.addColorStop(.65,'#080e13e8');g.addColorStop(1,'#080e1300');c.fillStyle=g;c.fillRect(0,0,w*.62,h)}else{g=c.createLinearGradient(0,0,0,h*.58);g.addColorStop(0,'#080e13');g.addColorStop(.55,'#080e13');g.addColorStop(1,'#080e1300');c.fillStyle=g;c.fillRect(0,0,w,h*.58)}
 const o=this.o;o.clearRect(0,0,w,h);const cx=w<701?w*.58:w*.69,cy=w<701?h*.64:h*.47;
 if(['time','advection','pressure','incompressibility','viscosity'].includes(kind)){o.strokeStyle='#bbd7cc44';o.lineWidth=1;for(let j=-2;j<=2;j++)for(let i=-2;i<=2;i++){const x=cx+i*38,y=cy+j*38,p=this.position(x,y),k=Math.max(0,Math.min(f.len-1,Math.round(p.x*n)+1+(Math.round(p.y*n)+1)*s));this.arrow(o,x,y,f.u[k]*90,f.v[k]*90,'#b8d9c888')}o.strokeStyle='#d9efab';o.beginPath();o.arc(cx,cy,kind==='incompressibility'?65:9,0,Math.PI*2);o.stroke();if(kind==='time'){const p=this.position(cx,cy),k=Math.floor(p.x*n)+1+(Math.floor(p.y*n)+1)*s;this.arrow(o,cx,cy,f.u[k]*300,f.v[k]*300,'#e5f3ba',2)}}
 if(kind==='cascade')this.cascade(o,cx,cy,scrub,t);
 if(kind==='singularity')this.singularity(o,cx,cy,scrub);
 }
 arrow(o,x,y,dx,dy,color,width=1){let a=Math.atan2(dy,dx),len=Math.hypot(dx,dy);if(len<2)return;o.strokeStyle=color;o.lineWidth=width;o.beginPath();o.moveTo(x,y);o.lineTo(x+dx,y+dy);o.lineTo(x+dx-5*Math.cos(a-.5),y+dy-5*Math.sin(a-.5));o.moveTo(x+dx,y+dy);o.lineTo(x+dx-5*Math.cos(a+.5),y+dy-5*Math.sin(a+.5));o.stroke()}
 cascade(o,cx,cy,q,t){const scale=this.w<701?.64:1;o.save();o.translate(cx,cy);o.scale(scale,scale);for(let level=0;level<4;level++){let alpha=Math.max(.1,Math.min(1,(q/100*4-level)+1)),count=2**level,r=64/Math.sqrt(count),x=-170+level*110;o.strokeStyle=`rgba(217,239,171,${alpha*.8})`;o.lineWidth=1.6;for(let k=0;k<count;k++){let y=(k-(count-1)/2)*Math.min(47,180/count);o.beginPath();for(let a=0;a<Math.PI*5;a+=.08){let rad=r*(1-a/(Math.PI*5));let px=x+Math.cos(a+t*(level+1)*.5)*rad,py=y+Math.sin(a+t*(level+1)*.5)*rad;if(a===0)o.moveTo(px,py);else o.lineTo(px,py)}o.stroke()}}o.font='11px sans-serif';o.fillStyle='#a7b4b8';o.fillText('LARGE EDDIES',-216,142);o.fillText('VISCOSITY → HEAT',100,142);o.restore()}
 singularity(o,cx,cy,q){const a=q/100,scale=this.w<701?.65:1;o.save();o.translate(cx,cy+55);o.scale(scale,scale);o.strokeStyle='#849d9955';o.lineWidth=1;o.beginPath();o.moveTo(-210,0);o.lineTo(215,0);o.stroke();o.strokeStyle='#d9efab';o.lineWidth=2;const width=75*(1-a)+5,height=35+185*a;o.beginPath();for(let x=-210;x<=210;x++){let y=-height*Math.exp(-(x*x)/(width*width));if(x===-210)o.moveTo(x,y);else o.lineTo(x,y)}o.stroke();o.font='12px sans-serif';o.fillStyle='#acbcb8';o.fillText('SMALLER REGION',-205,35);o.fillText('GREATER SPEED',70,-225);o.fillStyle='#d9efab';o.fillText(a>.94?'Beyond every finite bound?':'A possible concentration of motion',-120,75);o.restore()}
}
