// Each object is one scene. Interaction keys select controls and renderer overlays.
export const scenes = [
 {act:1,kicker:'THE BEAUTY OF FLUID MOTION',title:'A world<br>in <em>motion.</em>',caption:'A curl of smoke. A current in the ocean. All of this, held in one equation.',name:'A world in motion',kind:'hook',hint:'DRAG ANYWHERE TO STIR THE INK'},
 {act:1,kicker:'ONE EQUATION. A WHOLE WORLD.',title:'Meet the<br><em>Navier–Stokes.</em>',caption:'A tiny bit of fluid changes motion through transport, pressure, friction, and outside forces. The second line keeps its volume constant.',name:'The equation',kind:'equation',hint:'STIR THE FLUID BEHIND THE SYMBOLS'},
 {act:1,kicker:'01 / CHANGE OVER TIME',title:'Stay here.<br><em>Watch it change.</em>',caption:'At one fixed point, the arrow changes as the current passes. Stop time to catch a single moment.',name:'Change over time',kind:'time',term:'time',hint:'DRAG TO CHANGE THE CURRENT AT THE CROSSHAIR'},
 {act:1,kicker:'02 / SELF-TRANSPORT',title:'Motion carries<br><em>motion.</em>',caption:'Fluid carries its own velocity into new places. The flow reshapes the flow. This feedback is the nonlinear troublemaker.',name:'Self-transport',kind:'advection',term:'advection',hint:'STIR A CURVE. WATCH IT CARRY ITSELF'},
 {act:1,kicker:'03 / PRESSURE',title:'A push from<br><em>the neighbors.</em>',caption:'Pressure differences accelerate fluid from high to low. Switch off that correction: your strokes can pile fluid into places it cannot fit.',name:'Pressure',kind:'pressure',term:'pressure',hint:'DRAG INWARD TO CROWD THE FLUID'},
 {act:1,kicker:'04 / VISCOSITY',title:'Fast meets slow.<br><em>They share.</em>',caption:'Friction spreads momentum between neighbors. More viscosity softens sharp differences; less lets curls linger.',name:'Viscosity',kind:'viscosity',term:'viscosity',hint:'DRAW A SHARP TURN. WATCH IT SOFTEN'},
 {act:1,kicker:'05 / OUTSIDE FORCES',title:'Something gives<br><em>it a nudge.</em>',caption:'Gravity, buoyancy, or your hand can push a fluid. Here, buoyancy lifts the ink. Turn it off and stir a current yourself.',name:'Outside forces',kind:'force',term:'force',hint:'YOUR DRAG IS AN OUTSIDE FORCE TOO'},
 {act:1,kicker:'06 / INCOMPRESSIBILITY',title:'No room<br><em>to disappear.</em>',caption:'What flows into a tiny region must flow out. Pressure enforces this balance. Removing the constraint disables that same pressure correction.',name:'Incompressibility',kind:'incompressibility',term:'incompressibility',hint:'PUSH INK INTO THE MARKED REGION'},
 {act:1,kicker:'THE WHOLE IS MORE THAN THE PARTS',title:'Together,<br><em>it flows.</em>',caption:'Transport, pressure, friction, and outside forces work together. Remove an ingredient. Feel what each contributes.',name:'All together',kind:'assemble',hint:'TRY REMOVING ONE INGREDIENT'},
 {act:2,kicker:'01 / ORDER BECOMES UNREST',title:'When curls<br><em>make curls.</em>',caption:'Turn down viscosity and inertia takes over. Disturbances survive and interact. Higher Reynolds numbers reveal finer motion—until this little grid reaches its limits.',name:'The edge of turbulence',kind:'reynolds',hint:'MOVE THE SLIDER. THEN STIR'},
 {act:2,kicker:'02 / THE ENERGY CASCADE',title:'Big swirls.<br>Little <em>swirls.</em>',caption:'In three dimensions, large eddies pass energy toward smaller ones, until viscosity dissipates it as heat. Scrub the scale to follow the handoff.',name:'The energy cascade',kind:'cascade',hint:'A 3D CASCADE ILLUSTRATION · SCRUB THE SCALE'},
 {act:2,kicker:'03 / THE MILLION-DOLLAR QUESTION',title:'Can smooth flow<br><em>break itself?</em>',caption:'In 3D, must initially smooth flow stay smooth forever, or can a singularity form in finite time? Neither possibility is proved in general. $1 million awaits.',name:'The unsolved part',kind:'singularity',hint:'HYPOTHETICAL BLOW-UP · NOT A SIMULATED SOLUTION'},
 {act:2,kicker:'YOUR TURN / THE FLUID LAB',title:'Make a little<br><em>beautiful chaos.</em>',caption:'The ink is yours. Stir, interrupt, soften, and start again. A computer can approximate the motion. That is different from proving what happens forever.',name:'The fluid lab',kind:'sandbox',hint:'DRAG TO PAINT WITH MOTION'},
];
export const terms=[['time','Time evolution'],['advection','Self-transport'],['pressure','Pressure'],['viscosity','Viscosity'],['force','Outside forces'],['incompressibility','Volume constraint']];
